services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.6.2
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=_UNWsiuRV0U2P2X4oYJNFz-_xnwLqurdlqd6qsVkDoc=
      # Auto-create admin user
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _AIRFLOW_WWW_USER_FIRSTNAME=Emmanuel
      - _AIRFLOW_WWW_USER_LASTNAME=Umeogu
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - _AIRFLOW_WWW_USER_EMAIL=airflow@example.com
    command: >
      bash -c "
      airflow db init &&
      echo 'Initialization done'
      "

  airflow-webserver:
    image: apache/airflow:2.6.2
    restart: always
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=UdtQT_alHsxMDzkeZJzeGykkV_d_yZY011_34s9xM4g=
      - AIRFLOW__WEBSERVER__SECRET_KEY=_UNWsiuRV0U2P2X4oYJNFz-_xnwLqurdlqd6qsVkDoc=   
      - _PIP_ADDITIONAL_REQUIREMENTS=
    ports:
      - "8080:8080"
    command: webserver
 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
     

  airflow-scheduler:
    image: apache/airflow:2.6.2
    restart: always
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=UdtQT_alHsxMDzkeZJzeGykkV_d_yZY011_34s9xM4g=
      - AIRFLOW__WEBSERVER__SECRET_KEY=_UNWsiuRV0U2P2X4oYJNFz-_xnwLqurdlqd6qsVkDoc=  
      - _PIP_ADDITIONAL_REQUIREMENTS=
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs


volumes:
  postgres_data:

