version: "3.8"
services:
   #postgres database service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # redis service
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  #minio service
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.sample
    command: server /data --console-address ":9001" 
    volumes:
      - minio_data:/data
  #airflow init container
  airflow-init:
    image: apache/airflow:2.6.3
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .env.sample
    command: >
      bash -c "
      airflow db init &&
      echo 'Initialization complete.'"
  #airflow webserver container
  airflow-webserver:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow-init
    env_file:
      - .env.sample
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow webserver"
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../data:/opt/airflow/data
      - ../../logs:/opt/airflow/logs
    
  #airflow scheduler container
  airflow-scheduler:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow-webserver
    env_file:
      - .env.sample
    command: >
      bash -c "
      airflow scheduler"
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../data:/opt/airflow/data
      - ../../logs:/opt/airflow/logs
volumes:
  postgres_data:
  minio_data: